AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Style/NumberedParametersLimit:
  Max: 2
Style/MultilineBlockChain:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
