AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/LineLength:
  Max: 120
